### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by Windfarer** [hato-project/hato#3]
起步阶段的roadmap，建议以CI部分为主

**Comment by xuzhenglun** [comment]
Can do.

**Comment by renlulu** [comment]
建议先把这个 Feature 拆解一下，把mod 定好

**Comment by Windfarer** [comment]
@renlulu 这个只是一个原型，先随便写写实现了功能就可以，最终项目应该不会用它的结构

**Comment by tomwei7** [comment]
Hato 目标是想做成一个开源的 CI 工具开箱即用的那种，提供 Test, BUILD, Deploy 功能。为了照顾下我们这些 rust 渣渣，我们刚开始做个简单的原型试水，大概分成两个部分 hato, hato-worker：

hato:

* 管理项目接收 github webhook 
* 发送任务给 hato-worker

hato-worker:

* 运行 repo 内一个指定 bash 脚本并注入环境变量（GIT 信息等）
* 给 hato 反馈结果

写原型的时候 hato 和 hato-worker 甚至不需要分开，模块清晰就好了

**这只是个原型顺带熟悉下 rust，不要弄得太复杂**
